version: '3'
services:
  backend:
    image: kbdemiranda/planning-poker:corretto
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - app-network
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/postgres
      - USERNAME=postgres
      - PASSWORD=postgres
      - JWT_SECRET=1a2b3a4b5a6b7a8b9a10b11a12b13a14b15a16b17a18b19a20b21a22b23a


  database:
    image: kbdemiranda/postgres:bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge